//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mostofa_1249807.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public int catagorie_id { get; set; }
        public string product_name { get; set; }
        public string stock { get; set; }
        public decimal price { get; set; }
        public string picture { get; set; }
    
        public virtual category category { get; set; }
    }
}
